EM.Presentacion.WebAPI/Controllers/EventoController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EM.Dominio.Entity.Enum;
using EM.IServicio.Comprobante;
using EM.IServicio.Comprobante.DTOs;
using EM.IServicio.CreadorEvento;
using EM.IServicio.CreadorEvento.DTO;
using EM.IServicio.Entrada;
using EM.IServicio.Entrada.DTOs;
using EM.IServicio.Evento;
using EM.IServicio.Evento.DTOs;
using EM.IServicio.Fecha;
using EM.IServicio.Fecha.DTOs;
using EM.IServicio.FechaEvento;
using EM.IServicio.FechaEvento.DTOs;
using EM.IServicio.Helpers.Usuario;
using EM.IServicio.TarjetaDebito;
using EM.IServicio.TarjetaDebito.DTO;
using EM.IServicio.TipoEvento;
using EM.Servicio.Comprobante;
using EM.Servicio.CreadorEvento;
using EM.Servicio.Entrada;
using EM.Servicio.Evento;
using EM.Servicio.Fecha;
using EM.Servicio.FechaEvento;
using EM.Servicio.TarjetaDebito;
using EM.Servicio.TipoEvento;

namespace EM.Presentacion.WebAPI.Controllers
{
    public class EventoController : Controller
    {
        private readonly IEventoServicio _eventoServicio = new EventoServicio();
        private readonly ITipoEventoServicio _tipoEventoServicio = new TipoEventoServicio();
        private readonly IFechaServicio _fechaServicio = new FechaServicio();
        private readonly IFechaEventoServicio _fechaEventoServicio = new FechaEventoServicio();
        private readonly IEntradaServicio _entradaServicio = new EntradaServicio();
        private readonly ICreadorEventoServicio _creadorEventoServicio = new CreadorEventoServicio();
        private readonly IComprobanteServicio _comprobanteServicio = new ComprobanteServicio();
        private readonly ITarjetaDebitoServicio _tarjetaDebitoServicio = new TarjetaDebitoServicio();

        // GET: Evento
        public ActionResult Crear()
        {

            if (Session["Usuario"] != null)
            {
                _tipoEventoServicio.InsertarPorDefecto();

                ViewBag.ListaTipoEvento = _tipoEventoServicio.Get().ToList();

                //*************************************************************************//

                return View();

            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        public ActionResult Fecha(long id)
        {
            var fecha1 = _fechaEventoServicio.ObtenerPorIdEvento(id);

            var fecha2 = _fechaServicio.ObtenerPorId(fecha1.FechaId);

            return View(fecha2);
        }

        [HttpPost]
        public ActionResult Fecha(FechaDto fechaEventoDto)
        {

            _fechaServicio.Modificar(fechaEventoDto);

            return RedirectToAction("Perfil", "Persona");
        }

        public ActionResult SuspenderEvento(long id)
        {

            if (Session["Usuario"] != null)
            {
                var eventoView = EventoView(id);

                return View(eventoView);

            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        public ActionResult HabilitarEvento(long Id)
        {

            if (Session["Usuario"] != null)
            {

                _eventoServicio.EstadoActivo(Id);
                return RedirectToAction("PerfilEvento", new { id = Id });

            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        [HttpPost]
        public ActionResult SuspenderEvento(EventoViewDto dto)
        {
            try
            {
                _eventoServicio.EstadoSuspendido(dto.Id);
                return RedirectToAction("PerfilEvento", new {id = dto.Id});

            }
            catch (Exception e)
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Crear(EventoViewDto eventoViewDto, HttpPostedFileBase img)
        {


            if (img != null)
            {
                using (var reader = new BinaryReader(img.InputStream))
                {
                    eventoViewDto.Imagen = reader.ReadBytes(img.ContentLength);
                }
            }
            else
            {
                ViewBag.ErrorEvento = "Ingrese una Imagen para su evento.";
                return View();
            }


            ViewBag.ListaTipoEvento = _tipoEventoServicio.Get().ToList();

            if (ModelState.IsValid)
            {
                try
                {
                    if(!_eventoServicio.ValidarTitulo(eventoViewDto.Titulo))
                    {
                        if (!_eventoServicio.ValidarFecha(eventoViewDto.FechaEvento))
                        {
                            var evento = new EventoDto
                            {
                                Id = eventoViewDto.Id,
                                Titulo = eventoViewDto.Titulo,
                                Descripcion = eventoViewDto.Descripcion,
                                Mail = eventoViewDto.Mail,
                                Latitud = eventoViewDto.Latitud,
                                Longitud = eventoViewDto.Longitud,
                                TipoEventoId = eventoViewDto.TipoEventoId,
                                Orante = eventoViewDto.Orante,
                                Organizacion = eventoViewDto.Organizacion,
                                Domicilio = eventoViewDto.DomicilioCompleto,
                                Telefono = eventoViewDto.Telefono,
                                Imagen = eventoViewDto.Imagen
                            };

                            var EventoObj = _eventoServicio.Insertar(evento);

                            //*************************************************************//

                            var fecha = new FechaDto
                            {
                                FechaEvento = eventoViewDto.FechaEvento,
                                HoraInicio = eventoViewDto.HoraInicio,
                                HoraCierre = eventoViewDto.HoraFin
                            };

                            var FechaObj = _fechaServicio.Insertar(fecha);

                            //*************************************************************//

                            var fechaEvento = new FechaEventoDto
                            {
                                EventosId = EventoObj.Id,
                                FechaId = FechaObj.Id
                            };

                            _fechaEventoServicio.Insertar(fechaEvento);

                            //*************************************************************//

                            var entrada = new EntradaDto
                            {
                                Monto = eventoViewDto.Precio,
                                FechaDesde = DateTime.Now,
                                FechaHasta = DateTime.Now,
                                EventoId = EventoObj.Id,
                                Cantidad = 1
                            };

                            _entradaServicio.Insertar(entrada);

                            //*************************************************************//

                            var CreadorEvento = new CreadorEventoDto()
                            {
                                EventoId = EventoObj.Id,
                                UsuarioId = SessionActiva.UsuarioId,
                                Fecha = DateTime.Now
                            };

                            _creadorEventoServicio.Insertar(CreadorEvento);

                            //*************************************************************//

                            return RedirectToAction("ViewEvento", new { id = EventoObj.Id });

                        }
                        else
                        {
                            ViewBag.ErrorEvento = "Ingresa una fecha valida , anticipacion de 1 dia";
                            return View();
                        }
                    }
                    else
                    {
                        ViewBag.ErrorEvento = "El Titulo del evento ya esta siendo utilizada.";
                        return View();
                    }
                }
                catch (Exception e)
                {
                    ViewBag.ErrorEvento = "Ocurrio un error inesperado en el sistema";
                    return View();
                }
            }
            else
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult ViewEvento(long id)
        {
            if (Session["Usuario"] != null)
            {
                if (!_creadorEventoServicio.ValidarAlCreador(SessionActiva.UsuarioId,id))
                {
                    var eventoView = EventoView(id);

                    return View(eventoView);
                }
                else
                {
                    return RedirectToAction("PerfilEvento", new{ id = id});
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        [HttpGet]
        public ActionResult PerfilEvento(long id)
        {
            if (Session["Usuario"] != null)
            {

                if (_creadorEventoServicio.ValidarAlCreador(SessionActiva.UsuarioId, id))
                {
                    var eventoView = EventoView(id);


                    return View(eventoView);
                }
                else
                {
                    return RedirectToAction("ViewEvento", new { id = id });
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        public ActionResult GetImage(int id)
        {
            // fetch image data from database

            try
            {

EM.Presentacion.WebAPI/Views/Evento/BuscarEvento.cshtml
@using EM.IServicio.Evento;
@using EM.Servicio.Evento;
@{
    ViewBag.Title = "BuscarEvento";

    IEventoServicio _eventoServicio = new EventoServicio();

    var ListaAuxiliar = _eventoServicio.Obtener(ViewBag.Busqueda);

}

<link rel="stylesheet" type="text/css" href="~/Content/Login/css/util.css">
<link rel="stylesheet" type="text/css" href="~/Content/Login/css/main.css">

<div class="container">
    <div class="container-login100">
        <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
            <main role="main">
                <div class="container marketing">

                    <!-- Three columns of text below the carousel -->
                    <div class="row">

                        @foreach (var item in ListaAuxiliar)
                        {
                            <!-- xmlns="http://www.w3.org/2000/svg" -->
                            <div class="col-lg-4">

                                <!--<svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777" /><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>-->
                                <img src="@Url.Action("GetImage", new { id = @item.Id })" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" width="280" height="180" />
                                <h2>@item.Titulo</h2>
                                <p>@item.Descripcion</p>
                                <p><a class="btn btn-outline-success" href="~/Evento/ViewEvento/@item.Id" role="button">Ver Evento &raquo;</a></p>

                            </div>

                        }

                    </div>

                </div><!-- /.row -->
            </main>

        </div>
    </div>
</div>

EM.Presentacion.WebAPI/Views/Evento/Crear.cshtml
@using EM.IServicio.Evento
@using EM.IServicio.TipoEvento
@using EM.Servicio.Evento
@using EM.Servicio.TipoEvento
@model EM.IServicio.Evento.DTOs.EventoViewDto
@{
    ViewBag.Title = "CrearEvento";

    ITipoEventoServicio _tipoEventoServicio = new TipoEventoServicio();

    ViewBag.ListaTipoEvento = _tipoEventoServicio.Get().ToList();
}

<link href="~/Content/CrearEvento/css/style.css" rel="stylesheet" />
<link href="~/Content/CrearEvento/fonts/material-design-iconic-font/css/material-design-iconic-font.css" rel="stylesheet" />


<!--Load the API from the specified URL-->
<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyCFA0cdJHdJdccOiUiKNpwQ3wze89fWH38">
</script>

<body>

    <div class="wrapper">
        <div class="image-holder">
            <img src="~/Content/CrearEvento/images/form-wizard.png" alt="">
        </div>
        <form action="Crear" asp-controller="Evento" method="post" enctype="multipart/form-data">
            @if (ViewBag.ErrorEvento != null)
            {
                <div class="alert-danger" style='width:625px; height:30px'> @ViewBag.ErrorEvento </div>
            }
            <div id="wizard">
                <!-- SECTION 1 -->
                <h4></h4>
                <section>
                    <div class="form-row form-group">
                        <div class="form-row">
                            <label for="">
                                Nombre del Evento *
                            </label>
                            <span class="txt1 p-b-11" style="color:red">
                                @Html.ValidationMessageFor(x => x.Titulo)
                            </span>
                            <input type="text" class="form-control" name="Titulo">
                        </div>
                        <div class="form-row">
                            <label for="">
                                Quien dara la Charla? *
                            </label>
                            <span class="txt1 p-b-11" style="color:red">
                                @Html.ValidationMessageFor(x => x.Orante)
                            </span>
                            <input name="Orante" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-row">
                        <label for="">
                            Organizacion
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.Organizacion)
                        </span>
                        <input name="Organizacion" type="text" class="form-control">
                    </div>
                    <div class="form-row">
                        <label for="">
                            Tipo Evento *
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.TipoEventoId)
                        </span>
                        <div class="form-holder">

                            @Html.DropDownList("TipoEventoId", new SelectList(ViewBag.ListaTipoEvento, "Id", "Descripcion"), "Seleccionar Campo", new { @class = "form-control" })
                            <i class="zmdi zmdi-caret-down"></i>
                        </div>
                    </div>
                    <div class="form-row" style="margin-bottom: 18px">
                        <label for="">
                            Descripcion del Evento
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.Descripcion)
                        </span>
                        <textarea name="Descripcion" id="" class="form-control" placeholder="Ingrese una descripcion para su evento." style="height: 149px"></textarea>
                    </div>

                </section>

                <!-- SECTION 2 -->
                <h4></h4>
                <section>

                    <script>

                        var searchInput = 'search_input';

                        $(document).ready(function () {
                            var autocomplete;

                            autocomplete = new google.maps.places.Autocomplete((document.getElementById(searchInput)),
                                {
                                    types: ['geocode']
                                });

                            google.maps.event.addListener(autocomplete,
                                'place_changed',
                                function () {

                                    var near_place = autocomplete.getPlace();
                                    document.getElementById('latidude_input').value =
                                        near_place.geometry.location.lat();
                                    document.getElementById('longitude_input').value =
                                        near_place.geometry.location.lng();

                                    document.getElementById('latidude_view').innerHTML =
                                        near_place.geometry.location.lat();
                                    document.getElementById('longitude_view').innerHTML =
                                        near_place.geometry.location.lng();

                                });

                        });

                        $(document).on('change',
                            '#' + searchInput,
                            function () {

                                document.getElementById('latidude_input').value = '';
                                document.getElementById('longitude_input').value = '';
                                document.getElementById('latidude_view').innerHTML = '';
                                document.getElementById('longitude_input').innerHTML = '';

                            });

                    </script>

                    <div class="form-row">

                        <label>Localizacion:</label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.Latitud)
                        </span>

                        <input type="text" class="form-control" id="search_input" placeholder="Escriba cuidadosamente el lugar del Evento , evitar ENTER" />
                        <input type="hidden" id="latidude_input" name="Latitud" />
                        <input type="hidden" id="longitude_input" name="Longitud" />

                    </div>

                    <div class="form-row">

                        <p style="visibility: hidden"><b>Latitude:<span id="latidude_view"></span></b></p>
                        <p style="visibility: hidden"><b>Longitude:<span id="longitude_view"></span></b></p>

                    </div>

                    <div class="form-row">
                        <label for="">
                            Direccion *
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.DomicilioCompleto)
                        </span>
                        <input name="Calle" type="text" class="form-control" placeholder="Calle" style="margin-bottom: 20px">
                        <input name="CalleNumero" type="text" class="form-control" placeholder="Numero">
                    </div>

                    <div class="form-row">
                        <label for="">
                            Telefono *
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.Telefono)
                        </span>
                        <input name="Telefono" type="text" class="form-control">
                    </div>
                    <div class="form-row">
                        <label for="">
                            Email *
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.Mail)
                        </span>
                        <input type="text" class="form-control" name="Mail">
                    </div>

                    <br />
                </section>

                <!-- SECTION 3 -->
                <h4></h4>
                <section>
                    <div class="product">

                        <div class="item">
                            <div class="left">
                                <a href="#" class="thumb">
                                    <img src="~/Content/CrearEvento/images/ticket.png" alt="">
                                </a>
                                <div class="purchase">
                                    <h6>
                                        <a href="#">Valor de la Entrada</a>
                                    </h6>
                                    <span>x1</span>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="form-holder">
                        <label for="">
                            Precio *
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.Precio)
                        </span>
                        <div class="form-holder">
                            <input name="Precio" type="number" class="form-control">
                        </div>
                    </div>
                    <br />

                    <div class="checkout">
                        <p class="shipping">
                            <span class="heading">Informacion:</span>
                            Atencion si el evento es GRATUITO coloque como Valor = 0
                        </p>
                    </div>

                    <br />
                </section>

                <!-- SECTION 4 -->
                <h4></h4>
                <section>
                    <div class="form-holder">

                        <label class="active">
                            Agregue una Imagen para el Evento:
                        </label>
                        @Html.TextBox("img", null, new { type = "file" })

                    </div>

                    <br />
                    <div class="form-holder">
                        <label>
                            Fecha del Evento:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.FechaEvento)
                        </span>
                        <input name="FechaEvento" type="date" class="form-control">
                    </div>
                    <br />
                    <div class="form-holder">
                        <label>
                            Hora Inicio:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.HoraInicio)
                        </span>
                        <input name="HoraInicio" type="time" class="form-control">
                    </div>
                    <br />
                    <div class="form-holder">
                        <label>
                            Hora Fin del Evento:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.HoraFin)
                        </span>
                        <input name="HoraFin" type="time" class="form-control">
                    </div>
                    <br />
                    <br />
                    <div class="checkout">
                        <p class="shipping">
                            <span class="heading">Atencion:</span>
                            Antes De Finalizar Revise SI Todos Los DATOS SON CORRECTOS.
                        </p>
                    </div>

                    <div class="form-holder">
                        <button class="btn btn-outline-success" style="width: 150px; height: 50px;">
                            Finalizar
                        </button>
                    </div>

                </section>
            </div>
        </form>

    </div>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

</body>
<script src="~/Content/CrearEvento/js/jquery-3.3.1.min.js"></script>
<script src="~/Content/CrearEvento/js/jquery.steps.js"></script>
<script src="~/Content/CrearEvento/js/main.js"></script>
<!-- Template created and distributed by Colorlib -->

EM.Presentacion.WebAPI/Views/Evento/Fecha.cshtml
@model EM.IServicio.Fecha.DTOs.FechaDto
@{
    ViewBag.Title = "Fecha";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/css/util.css">
<link rel="stylesheet" type="text/css" href="~/Content/Login/css/main.css">

<body>

    <div class="limiter">
        <div class="container-login100">

            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">

                <h1>Modificacion Del Horario Del Evento</h1>
                <br />
                <form asp-action="Fecha" asp-controller="Evento" method="post">

                    <div class="form-holder">
                        <label>
                            Fecha del Evento:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.FechaEvento)
                        </span>
                        @Html.EditorFor(model => model.FechaEvento, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <br />
                    <div class="form-holder">
                        <label>
                            Hora Inicio:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.HoraInicio)
                        </span>
                        @Html.EditorFor(model => model.HoraInicio, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <br />
                    <div class="form-holder">
                        <label>
                            Hora Fin del Evento:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.HoraCierre)
                        </span>
                        @Html.EditorFor(model => model.HoraCierre, new { htmlAttributes = new { @class = "form-control" } })                       
                    </div>
                    <br />
                    
                    
                    @*<div class="form-holder">
                        <label>
                            Fecha del Evento:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.FechaEvento)
                        </span>
                        <input name="FechaEvento" type="date" value="@Model.FechaEvento" class="form-control">
                    </div>
                    <br/>
                    <div class="form-holder">
                        <label>
                            Hora Inicio:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.HoraInicio)
                        </span>
                        <input name="HoraInicio" type="time" value="@Model.HoraInicio" class="form-control">
                    </div>
                    <br/>
                    <div class="form-holder">
                        <label>
                            Hora Fin del Evento:
                        </label>
                        <span class="txt1 p-b-11" style="color:red">
                            @Html.ValidationMessageFor(x => x.HoraCierre)
                        </span>
                        <input name="HoraFin" type="time" value="@Model.HoraCierre" class="form-control">
                    </div>*@
                    <button class="btn btn-outline-primary" style="margin-left:110px">Guardar Cambios</button>

                </form>

            </div>
        </div>
    </div>

</body>