EM.Presentacion.WebAPI/Controllers/APIs/CondicionIvaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using EM.Dominio.Entity.Entidades;
using EM.Repositorio;
using EM.Repositorio.Base;

namespace EM.Presentacion.WebAPI.Controllers.APIs
{
    public class CondicionIvaController : ApiController
    {
        private readonly IRepositorio<CondicionIva> _repositorio = new Repositorio<CondicionIva>();

        [HttpGet]
        public IEnumerable<CondicionIva> ObtenerTodo()
        {
            return _repositorio.GetAll().ToList();
        }

        [HttpGet]
        public IEnumerable<CondicionIva> ObtenerPorFiltro(string cadena)
        {
            return _repositorio.GetByFilter(x => x.Descripcion.Contains(cadena)
                                                 || x.Codigo.ToString().Contains(cadena)).ToList();
        }



    }
}

EM.Presentacion.WebAPI/Controllers/CondicionIvaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EM.IServicio.CondicionIva;
using EM.IServicio.CondicionIva.DTOs;
using EM.Servicio.CondicionIva;

namespace EM.Presentacion.WebAPI.Controllers
{
    public class CondicionIvaController : Controller
    {
        private ICondicionIvaServicio _condicionIvaServicio = new CondicionIvaServicio();

        // GET: CondicionIva
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CondicionIvaDto condicionIva)
        {
            if (ModelState.IsValid)
            {
                _condicionIvaServicio.Insertar(condicionIva);
            }

            return View();
        }
    }
}

EM.Presentacion.WebAPI/Views/CondicionIva/Create.cshtml
@model EM.IServicio.CondicionIva.DTOs.CondicionIvaDto
@{
    ViewBag.Title = "Create";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/animate/animate.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/select2/select2.min.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="~/Content/Login/css/util.css">
<link rel="stylesheet" type="text/css" href="~/Content/Login/css/main.css">


<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                <form class="login100-form validate-form flex-sb flex-w" asp-action="Create" asp-controller="CondicionIva" method="post">
                    <span class="login100-form-title p-b-32">
                        Agregue una Descricpion
                    </span>

                    <span class="txt1 p-b-1">
                        Descripcion Del Condicion Iva
                    </span>
                    <div class="wrap-input100 validate-input m-b-36" data-validate="Descripcion Requerido">
                        <input asp-for="Descripcion" class="input100" type="text" name="Descripcion">
                        <span class="focus-input100"></span>
                    </div>


                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Crear
                        </button>
                    </div>

                </form>

            </div>
        </div>
    </div>

    <div id="dropDownSelect1"></div>

</body>

<!--===============================================================================================-->
<script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/bootstrap/js/popper.js"></script>
<script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/daterangepicker/moment.min.js"></script>
<script src="~/Content/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="~/Content/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="~/Content/js/main.js"></script>